### PR TITLE
Enable continuous integration

### PR DESCRIPTION
**Pull request by bvanassche**
Detect portability issues more quickly by letting the Github infrastructure build sg3_utils for multiple platforms upon every push and pull request.

### CODE REVIEW

**Comment by doug-gilbert** [comment]
Thanks for the patches. I have applied the sg_dd upstream. The sg_turs one would not be my preference, it weighs down the sg_turs utility on all platforms. I have added a SG_LIB_MINGW conditional and if true the windows.h Sleep() function is called instead (it takes milliseconds as its unit). Is that problem only on MinGW 32 bit?
Now the third one, I need to do more research on that as I don't want that done on my development machine. My upstream repository is subversion and new revisions are bounced through a 'git svn' repository with 'git svn rebase'. Then I push those changes to the remote which is https://github.com/doug-gilbert/sg3_utils . So is that done on github and my development machine or just github? That 'git svn rebase' is a sort of pull (from a subversion repository); does it trigger the 'on: [push, pull_request]' in the CI script?

**Comment by bvanassche** [comment]
Please note that host name `x86_64-w64-mingw32` selects the [MinGW-w64](https://www.mingw-w64.org/) environment. That environment includes a 64-bit compiler.

As far as I know the sg_turs patch is only required for MinGW.

Any files in the .github directory do not affect the local development workflow. The files in that directory control how the github server is configured. Local git commands like `git svn rebase` treat the contents of the .github directory as a bunch of text files just like e.g. .h or .c source code.

**Review by doug-gilbert — APPROVED** [review]
Lets see how this goes ... Nowhere. Seems I can't just take the third commit. The first two have been applied upstream and are already in place (but the sg_turs one is a bit different). So could you make a new pull request with just the CI part. Testing for FreeBSD clean compile would be a great addition.

**Comment by bvanassche** [comment]
I have dropped my sg_turs patch and added three new patches in addition to the continuous integration patch. Please take another look.

**Comment by doug-gilbert** [comment]
So that worked. Plus I was able to get those changes back to my local git repo (with 'git pull origin master') and then from there into my upstream svn repo (with 'git svn dcommit --rmdir' (so obvious, not)). Never been down that "reverse" path before. Made a few small changes upstream to send a test commit back to github. It took a while to do the CI, but it was all good. Thanks!

**Pull request merged**
